### ISSUE TITLE
Collect TODO List

### ISSUE THREAD

**Issue by KyleKing** [KyleKing/dash_charts#12]
- [ ] Show pareto as stacked bar chart, see: https://plotly.com/python/bar-charts/#stacked-bar-chart `fig.update_layout(barmode='stack')`
- [ ] Finish implementing `implements` for cleaner interfaces
- [ ] TODO: Add DataCache and store meta tables to the README (and implement an example)
- [ ] PLANNED: app_px
	- [ ] Add tab to view preview of all data frames found in px
	- [ ] Add ability to select data source (CSV, JSON, SQlite, etc.) with upload module
		- [ ] data upload is in top bar where user can use dcc.upload to pick the file - https://dash.plot.ly/dash-core-components/upload
		- [ ] Maybe modal appears on load to select how to tidy data, how to load (is JSON in records or other format?) or which table from SQL to load
		- [ ] Button to toggle back to the default data set per chart
	- [ ] Show general data statistics from pandas describe!
- [ ] PLANNED: sparklines (status: nothing right now)
	- [ ] create new sparklines figures
- [ ] PLANNED: ESRI Inspiration:
	- [ ] View guidelines on TS from ESRI: https://doc.arcgis.com/en/operations-dashboard/help/serial-chart.htm
		- [ ] Maybe update rolling chart to use recommendations from ESRI?
	- [ ] Build indicator like in ESRI: https://doc.arcgis.com/en/operations-dashboard/help/indicator.htm
	- [ ] Built ESRI Event list: https://doc.arcgis.com/en/operations-dashboard/help/list.htm
- [ ] [Add "Gallery" to documentation site like matplotlib](https://smarie.github.io/mkdocs-gallery/generated/gallery/)
